services:
  bot:
    container_name: app-voltr-finance
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    env_file:
      - .env
    networks:
      - postgres-network
  migrate:
    image: ghcr.io/amacneil/dbmate
    command: ["up"]
    volumes:
      - ./db:/db:rw
    env_file:
      - .env.dbmate
    networks:
      - postgres-network
    profiles:
      - migrate
volumes:
  db_data:
networks:
  postgres-network:
    external: true
