services:
  bot:
    container_name: voltr-bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./cmd:/app/cmd:rw
      - ./internal:/app/internal:rw
      - ./.dev:/app/.dev:rw
    environment:
      - DB_USER=voltr
      - DB_PASSWORD=voltr
      - DB_NAME=voltr_finance
      - DB_HOST=db
      - DB_PORT=5432
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3100:3100"
  db:
    image: postgres
    container_name: voltr-db
    environment:
      POSTGRES_USER: voltr
      POSTGRES_PASSWORD: voltr
      POSTGRES_DB: voltr_finance
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
      # - ./database/data:/docker-entrypoint-initdb.d
  migrate:
    image: ghcr.io/amacneil/dbmate
    entrypoint: ["sh", "/db/init.sh"]
    volumes:
      - ./db:/db:rw
    depends_on:
      - db
    environment:
      - DB_USER=voltr
      - DB_PASSWORD=voltr
      - DB_NAME=voltr_finance
      - DB_HOST=db
      - DB_PORT=5432
volumes:
  db_data: